### Create a new store
POST http://localhost/api/stores
Content-Type: application/json
Accept: application/json

{
    "name": "Some Store Name",
    "products": [
        {
            "name": "Sample Product 1",
            "quantity": 10
        }
    ]
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Get all stores
GET http://localhost/api/stores
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get a specific store
GET http://localhost/api/stores/some-store-id-1
Accept: application/json
###

### Update a store
PUT http://localhost/api/stores/some-store-id-1
Content-Type: application/json
Accept: application/json

{
    "name": "Updated Shop Name",
    "products": [
        {
            "id": "some-product-id-1",
            "name": "Updated Product 1",
            "quantity": 20
        }
    ]
}
###

### Delete a store
DELETE http://localhost/api/stores/some-store-id-1
Accept: application/json
###

### Sell a product from a store
POST http://localhost/api/stores/some-store-id-1/product/some-product-id-1/sell
Accept: application/json
###
